// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:679095097510:web:b7281115b55983c09e7c67',
    messagingSenderId: '679095097510',
    projectId: 'farmtrack-13bd7',
    authDomain: 'farmtrack-13bd7.firebaseapp.com',
    storageBucket: 'farmtrack-13bd7.firebasestorage.app',
    measurementId: 'G-99TSHJ2V9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDujRn5aV1wDEZWUdkZ0l4lQvJpQaJjdzE',
    appId: '1:679095097510:android:34b59705864b52989e7c67',
    messagingSenderId: '679095097510',
    projectId: 'farmtrack-13bd7',
    storageBucket: 'farmtrack-13bd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1NlpSd0jKnRKZHyzVLDCeyHdRwyH_roE',
    appId: '1:679095097510:ios:ab3bd639ec9806b89e7c67',
    messagingSenderId: '679095097510',
    projectId: 'farmtrack-13bd7',
    storageBucket: 'farmtrack-13bd7.firebasestorage.app',
    iosBundleId: 'com.example.farmtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1NlpSd0jKnRKZHyzVLDCeyHdRwyH_roE',
    appId: '1:679095097510:ios:ab3bd639ec9806b89e7c67',
    messagingSenderId: '679095097510',
    projectId: 'farmtrack-13bd7',
    storageBucket: 'farmtrack-13bd7.firebasestorage.app',
    iosBundleId: 'com.example.farmtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzVWU5fcMHetAuv1gzmM-6tDi9vEqEEOg',
    appId: '1:679095097510:web:d84a7a5f490f64779e7c67',
    messagingSenderId: '679095097510',
    projectId: 'farmtrack-13bd7',
    authDomain: 'farmtrack-13bd7.firebaseapp.com',
    storageBucket: 'farmtrack-13bd7.firebasestorage.app',
    measurementId: 'G-WY7CPZFSX9',
  );
}
